{{- with .Values.config.oidc }}
{{- if .secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
type: Opaque
data:
{{- with .clientID }}
  clientID: {{ . | b64enc | quote }}
{{- end }}
{{- with .clientSecret }}
  clientSecret: {{ . | b64enc | quote }}
{{- end }}
{{- with .issuerURL }}
  issuerURL: {{ . | b64enc | quote }}
{{- end }}
{{- with .scopes }}
  scopes: {{ . | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
