### required for mac os initial setup: ###
### ---------------------------------- ###

# Administrator's username for Git (string)
git_admin_email: schlafdata@gmail.com

# Administrator's username for Git (string)
git_admin_username: jschlafdata

# Name of your project or company (string)
project_name: portalai

### ********************************** ###
### ---------------------------------- ###


# AWS SSO login URL (string)
aws_start_url: 

# Name of the data portal created (string)
data_portal_name: One Portal to Rule them All

cost:
  - 0.0376
  - 0.0208
  - 0.0416

k8s_deployment_size: 
  smol_fry: true
  med_fy: false
  large_fry: false
  supersize_me: false


# Link to the Git repository for MAGE AI Portal (string)
# you can use this open source example to see test ETL pipelines.

mage_git_repo_link: 

# AWS resource prefix, must not contain '-' (string)
aws_prefix: portalai

# DNS Zone IDs and details for different environments (development, stage, production)
dns_zone_id:
  dev:
    domain: schlaf-data
    dns_domain: schlaf-data.engineering
    dns_zone: Z00777581CD3CU97IP3IQ
  stage:
    domain: 
    dns_domain: 
    dns_zone: 
  prod:
    domain: 
    dns_domain: 
    dns_zone: 

# AWS environment configurations
aws_environments:
  dev:
    aws_region: us-east-1
    prefix: dev
    s3_prefix: "-dev"
    tfstate: portalai.tfstate
    vpc_cidr: 174.64.0.0/16
    public_subnet_cidr: 174.64.1.0/23
    private_subnet_cidr: 174.64.10.0/23
  stage:
    aws_region: 
    prefix: 
    s3_prefix: 
    vpc_cidr: 
    public_subnet_cidr: 
    private_subnet_cidr: 
  prod:
    aws_region: 
    prefix: 
    s3_prefix: 
    vpc_cidr: 
    public_subnet_cidr: 
    private_subnet_cidr: 


# Initial GPU node group for Kubernetes (list of objects)
## Start with at least one initial GPU node for k8s.
## recommended to start with g5, as they are the most
## cost efficient when considering power & output.


included_gpu_node_groups:
- g5
# - g4dn
# - p2
# - p3
# - p3dn
# - p4d
# - p5

# OpenVPN configurations (object)
ovpn_configs:
  istance_type: t3.small
  users: # List of usernames to create VPN authentication files for (list of strings)
  - john

# PostgreSQL RDS configuration (object)
postgres_rds:
  db_user: rds_admin
  app_name: portalai
  generated_token_file: rds.env
  instance_type: db.t3.micro


## OPTIONAL ADDITIONAL SETTINGS:

# Additional DNS zones configuration (object, optional)
additional_dns_zones:
  include: false # or false (boolean)
  zones:
    dev: # list of strings
    -
    -
    -
    stage:
    prod:

helm_deployments:
  required:
  - wildcard-certificate
  - nginx-internal
  - external-dns
  - vault
  - external-secrets
  - eso-secrets-operators
  - efs
  - efs-csi
  - tls-reflections
  optional:
    mageai:
      include:
        charts:
      exclude:
        charts:
        - mageai
        - mageai-workspaces
    atlantis:
      include:
        charts:
        - atlantis
      exclude:
        charts:
    monitoring:
      include:
        charts:
      exclude:
        charts:
        - k8s-dashboard
        - grafana
        - kube-state-metrics
        - prometheus
        - prometheus-node-exporter
    dashoards:
      include:
        charts:
      exclude:
        charts:
        - metabase
    llms:
      include:
        charts:
      exclude:
        charts:
    system:
      include:
        charts:
        - nginx-external
      exclude:
        charts:
        - jupyter-lab-accelerated
        - llm-models
    apps:
      include:
        charts:
      exclude:
        charts:
        - websites
