
efs_csi_requests:
  replicaCount: 1
  sidecars:
    nodeDriverRegistrar:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
    livenessProbe:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
    csiProvisioner:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
  controller:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
  node:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"

external_secrets_requests:
  replicaCount: 1
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
  webhook:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
  certController:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"

vault_requests:
  injector:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    agentDefaults:
      cpuLimit: "100m"
      cpuRequest: "25m"
      memLimit: "128Mi"
      memRequest: "32Mi"
  server:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
  csi:
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    agent:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"

external_dns_requests:
  resources:
  requests:
    memory: "10Mi"
    cpu: "10m"


nginx_internal_requests:
  controller:
    replicaCount: 1
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    admissionWebhooks:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
    patchWebhookJob:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"

nginx_external_requests:
  controller:
    replicaCount: 1
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    admissionWebhooks:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
    patchWebhookJob:
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"