apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
  {{- if .Values.medusaPorts.haproxy.include }}
  {{- range .Values.medusaPorts.haproxy.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  {{- end }}
  {{- if .Values.medusaPorts.socks.include }}
  {{- range .Values.medusaPorts.socks.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  {{- end }}
  {{- if .Values.medusaPorts.http.include }}
  {{- range $index, $port := .Values.medusaPorts.http.ports }}
  - name: http{{ $index }}
    port: {{ $port }}
    protocol: TCP
    targetPort: {{ $port }}
  {{- end }}
  {{- end }}