## paths for yml config files. 

config_paths:
  global_config_base: global_settings.yml
  aws_efs: portal_ai/configs/constants/aws/efs.yml
  aws_ubuntu: portal_ai/configs/constants/aws/ubuntu_images.yml
  accelerated_instances: portal_ai/configs/constants/aws/accelerated_instances.yml
  constant_config: portal_ai/configs/constants/portal-ai/constants.yml

jinja_template_paths:
  global_settings_base: 
    template_path: portal_ai/templating/templates/global_settings_base.tmpl.j2
  aws_settings_base: 
    template_path: portal_ai/templating/templates/aws_base_outputs.tmpl.j2
    render_funcs: 
    - get_iam_policy_arns
    - get_subnet_values
  kops_settings_base:
    template_path: portal_ai/templating/templates/kops_settings_base.tmpl.j2
    render_funcs: 
    - kops_iam_policies
    - compact_subnets
    - defaultdict_to_dict
  kops_cluster_base:
    template_path: portal_ai/templating/templates/kops_cluster_config.tmpl.j2
  kops_instance_groups_base:
    template_path: portal_ai/templating/templates/kops_instance_groups_config.tmpl.j2
  helm_settings_base:
    template_path: portal_ai/templating/templates/helm_chart_values.tmpl.j2
  rbac_settings_base:
    template_path: portal_ai/templating/templates/mage_rbac_backend.tmpl.j2


generated_output_paths:
  global_settings_base: 
  - portal_ai/configs/generated/global_settings_base.yml
  - portal_ai/terraform/aws_base/global_settings_base.yml
  aws_settings_base:
  - portal_ai/configs/generated/aws+global_settings_base.yml
  kops_settings_base:
  - portal_ai/configs/generated/kops_settings_base.yml
  kops_cluster_base:
  - portal_ai/configs/generated/kops_cluster_base.yml
  - portal_ai/kops/kops_cluster_base.yml
  helm_settings_base: 
  - portal_ai/configs/generated/helm_values_base.yml
  - portal_ai/terraform/helm/configs/deployment_settings.yml

generated_load_paths:
  global_settings_base: portal_ai/configs/generated/global_settings_base.yml
  aws_settings_base: portal_ai/terraform/aws_base/generated/module_outputs.json
  aws_plus_global_base:  portal_ai/configs/generated/aws+global_settings_base.yml
  kops_settings_base: portal_ai/configs/generated/kops_settings_base.yml
  helm_deployment_settings: portal_ai/terraform/helm/configs/deployment_vars.yaml

# these are constants required for application to work.
# ** WIP to allow for changing these in the future. **

# prefixes for s3 buckets and aws resources created.
# example: kops state store: kops-[environment].[dns_domain]
# terraform state store: tfstate-[environment].[dns_domain]

remote_s3_buckets:
  kops_state_prefix: kops
  tfstate_prefix: tfstate
  kops_iam_prefix: iam-http-dir
  global_manifest: project-manifest

# Directory '/Users/[user_name]/.ssh/[project_name]' was created.
# secrets necessary to initialize applications are stored here
# you can update/ move/ rotate as needed after deploying.

ssh_key_names:
  - openvpn
  - kops
  - git

# OpenVPN configurations (object)
open_vpn_static_route_ip: "10.8.0.0/24"

# the base for kubernetes master and worker nodes
k8s_deployment_settings:
  smol_fry:
    masterMachineType: t3.medium
    nodeMachineType: m5.large
    podIdentityReplicas: 1
    mixedInstancesPolicy: 
      instances:
      - m5.large
      - m5a.large
      - m6a.large
      - m7a.large
    gpuMixedInstancesPolicy:
      instances:
      - g3.8xlarge
      - g4dn.xlarge
      - g5.xlarge
      - p3.2xlarge
      igName: spot-group
      gpus: 1
      gpuMachineType: g5.xlarge
      gpuMaxNodeSize: 1
    maxNodeSize: 1
    zones: 1
    azs: 
  med_fy:
    masterMachineType: m5.large
    nodeMachineType: t3.medium
    maxNodeSize: 3
    zones: 1
    azs: 
  large_fry:
    masterMachineType: m5.large
    nodeMachineType: m5.large
    maxNodeSize: 3
    zones: 1
    azs: 
  supersize_me:
    masterMachineType: m5.large
    nodeMachineType: m5.large
    maxNodeSize: 3
    zones: 3
    azs: 
