local_custom.apps.llm-models: false
local_custom.apps.mageai-workspaces: true
local_custom.apps.jupyter-lab-accelerated: false
local_custom.apps.websites: false
local_custom.system.wildcard-certificate: true
local_custom.system.external-secrets: true
external.apps.mageai: true
external.apps.metabase: false
external.apps.k8s-dashboard: false
external.system.nginx-internal: true
external.system.external-dns: true
external.system.efs-csi: true
external.system.nginx-external: false
external.system.efs: true
external.system.vault: true
external.monitoring.kube-state-metrics: true
external.monitoring.prometheus-node-exporter: true
external.monitoring.grafana: true
external.monitoring.prometheus: true
