apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tools-{{ .Values.commonName }}
  namespace: "default"
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitor,ext,web,gpu,de"
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "{{ .Values.aliasCommonName }}"
  dnsNames: 
    - "{{ .Values.aliasCommonName }}"
  {{- range .Values.subdomains }}
    - "*.{{ . }}.{{ $.Values.dnsDomain }}"
  {{- end }}