kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: headlamp-rolebinding
  namespace: monitor
subjects:
- kind: ServiceAccount
  name: headlamp
  namespace: monitor
roleRef:
  kind: Role
  name: headlamp-role
  apiGroup: rbac.authorization.k8s.io