apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: eso-backend
    creationPolicy: Owner
    template:
      metadata: 
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "mageai,monitoring,internal-apps,external-apps,gpu-apps"
  data:
    - secretKey: rds_username
      remoteRef:
        key: eso/helm
        property: pg_user
    - secretKey: rds_password
      remoteRef:
        key: eso/helm
        property: pg_pass
    - secretKey: mageconnurl
      remoteRef:
        key: eso/helm
        property: mageconnurl
    - secretKey: rds_host
      remoteRef:
        key: eso/helm
        property: pg_host

