apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: eso-backend
    creationPolicy: Owner
    template:
      metadata: 
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitor,ext,web,gpu,de"
  data:
    - secretKey: rds_username
      remoteRef:
        key: eso/helm
        property: pg_user
    - secretKey: rds_password
      remoteRef:
        key: eso/helm
        property: pg_pass
    - secretKey: mageconnurl
      remoteRef:
        key: eso/helm
        property: mageconnurl
    - secretKey: rds_host
      remoteRef:
        key: eso/helm
        property: pg_host
    - secretKey: hf_token
      remoteRef:
        key: eso/helm
        property: hf_token
    - secretKey: gh_token
      remoteRef:
        key: eso/helm
        property: gh_token
    - secretKey: app_admin
      remoteRef:
        key: eso/helm
        property: app_admin
