apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-eso-secret
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.jobRole }}
      containers:
      - name: wait-for-secret
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          until kubectl get secret $SECRET_NAME -n $NAMESPACE; do
            echo "Waiting for TLS secret '$SECRET_NAME' to be created..."
            sleep 10
          done
          echo "TLS secret '$SECRET_NAME' found."
        env:
        - name: SECRET_NAME
          value: eso-backend
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
      restartPolicy: Never
  backoffLimit: 6