spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-file-envvars: "envvars"
        vault.hashicorp.com/agent-inject-secret-envvars: "internal/data/data_engineering"
        vault.hashicorp.com/agent-inject-template-envvars: |
          {{- with secret "internal/data/data_engineering" -}}
          {{ .Data | toUnescapedJSON }}
          {{- end }}
        vault.hashicorp.com/agent-limits-ephemeral: ""
        vault.hashicorp.com/role: "mageai"