spec:
  template:
    spec:
      containers:
      - name: development-container
        env:
        - name: USER_CODE_PATH
          value: "/home/src/development"
        - name: HIDE_ENV_VAR_VALUES
          value: "0"
        - name: GIT_SSH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: eso-backend
              key: git_public_key
        - name: GIT_SSH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: eso-backend
              key: git_private_key
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: eso-backend
              key: rds_username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: eso-backend
              key: rds_password
        envFrom:
        - configMapRef:
            name: dev-env-config-map
        workingDir: "/home/src/development"