ubuntu_latest_jammy:
  ap-northeast-1:
    image_ami: ami-0e00e89380cb2a63b
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ap-northeast-2:
    image_ami: ami-05f82245cbdf5daa7
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ap-northeast-3:
    image_ami: ami-076b1577f815a0e3a
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ap-south-1:
    image_ami: ami-0ddf51b8a2b282a3d
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ap-southeast-1:
    image_ami: ami-0868aa3dfd305c7d0
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ap-southeast-2:
    image_ami: ami-0ddc5249fca511c94
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  ca-central-1:
    image_ami: ami-06aaee54f1c7fb715
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  eu-central-1:
    image_ami: ami-099245c5effbaf603
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  eu-north-1:
    image_ami: ami-0407a4995711db777
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  eu-west-1:
    image_ami: ami-01dbabda256db26e7
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  eu-west-2:
    image_ami: ami-0660cbd2af1273a49
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  eu-west-3:
    image_ami: ami-08ed95ff0b0be68d1
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  sa-east-1:
    image_ami: ami-01cc5b3d73b604084
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  us-east-1:
    image_ami: ami-0ba8e031ca32ab37f
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  us-east-2:
    image_ami: ami-097be5247ed769f68
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  us-west-1:
    image_ami: ami-0208b2eb1c17d9733
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708
  us-west-2:
    image_ami: ami-005414fb846dc12d1
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220708