ubuntu_latest_jammy:
  us-west-2:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-008fe2fc65df48dac
  ap-south-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-03f4878755434977f
  eu-west-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0905a3c97561e0b69
  eu-north-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0014ce3e52359afbd
  us-east-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0c7217cdde317cfec
  ca-central-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0a2e7efb4257c0907
  us-west-2-ubuntu-jammy:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-008fe2fc65df48dac
  ap-northeast-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-07c589821f2b353aa
  ap-southeast-2:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-04f5097681773b989
  ap-northeast-3:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-05ff0b3a7128cd6f8
  ap-southeast-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0fa377108253bf620
  ap-northeast-2:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0f3a440bbcff3d043
  us-east-2:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-05fb0b8c1424f266b
  eu-west-2:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0e5f882be1900e43b
  eu-central-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0faab6bdbac9486fb
  us-west-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0ce2cb35386fc22e9
  sa-east-1:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-0fb4cf3a99aa89f72
  eu-west-3:
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
    image_ami: ami-01d21b7be69801c2f