apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-url-response
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.jobRole }}
      containers:
      - name: python-container
        image: python:3.8-slim
        command: ["sleep"]
        args: ["infinity"]
        env:
        - name: URL
          value: {{ .Values.vaultUrl }}
      restartPolicy: Never
  backoffLimit: 30