server:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: vault.principalcg.cloud
      meta.helm.sh/release-name: vault-ingress
      meta.helm.sh/release-namespace: default
      nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    labels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/name: vault
    ingressClassName: nginx-internal
    pathType: Prefix
    hosts:
    - host: vault.principalcg.cloud
      paths:
      - /
    tls:
    - hosts:
      - vault.principalcg.cloud
      secretName: wildcard-tls-cert-principalcg-cloud
  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: /vault/data
    storageClass: vault-sc
    accessMode: ReadWriteOnce
    annotations: {}
    labels: {}
