apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gitBranch }}-env-config-map
data:
  GIT_AUTH_TYPE: ssh
  GIT_REPO_LINK: {{ .Values.mageGitRepoLink }}
  GIT_REPO_PATH: /home/src/{{ .Values.workspace_name }}
  GIT_USERNAME: {{ .Values.gitAdminUsername }}
  GIT_EMAIL: {{ .Values.gitAdminEmail }}
  dbt_env: {{ .Values.dbtEnv }}
  ENV: {{ .Values.gitBranch }}
  MAGE_REPO_ENV: {{ .Values.workspace_name }}
  AWS_DEFAULT_REGION: {{ .Values.awsRegion }}
  GIT_SYNC_ON_START: "0"
  GIT_SYNC_ON_EXECUTOR_START: "0"
  GIT_SYNC_SUBMODULES: "0"