apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.service_account_name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          workingDir: /
          ports:
          - containerPort: {{ .Values.service.port }}
            name: notebook
          env:
          - name: JUPYTER_PORT
            value: "8889"
          - name: JUPYTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eso-backend
                key: app_admin
          volumeMounts:
          - mountPath: /data
            name: model
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.Name }}
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}