{{- if .Values.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: s3-manager
  namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}