{{- $esoSecret := .Values.eso_mirror.esoSecret -}}
{{- range .Values.eso_mirror.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $esoSecret }}
  namespace: {{ . }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: {{ printf "default/%s" $esoSecret }}
data:
---
{{- end }}