apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: external-apps
  name: event-writer
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-writer-binding
  namespace: external-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-writer
subjects:
- kind: ServiceAccount
  name: aws-lb-controller
  namespace: default