apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.ports.containerPort.port }}
    targetPort: {{ .Values.ports.containerPort.targetPort }}
    protocol: TCP
    name: {{ .Values.release_suffix }}
  selector:
    app: {{ .Release.Name }}