apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: eso-backend
    creationPolicy: Owner
  data:
    - secretKey: rds_username
      remoteRef:
        key: eso/helm
        property: pg_user
    - secretKey: rds_password
      remoteRef:
        key: eso/helm
        property: pg_pass
    - secretKey: mageconnurl
      remoteRef:
        key: eso/helm
        property: mageconnurl
    - secretKey: git_private_key
      remoteRef:
        key: eso/helm
        property: git_private_key
    - secretKey: git_public_key
      remoteRef:
        key: eso/helm
        property: git_public_key
    - secretKey: mage_db
      remoteRef:
        key: eso/helm
        property: rds_database