apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tools-{{ .Values.commonName }}
  namespace: default
spec:
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "{{ .Values.aliasCommonName }}"
  dnsNames: 
    - "{{ .Values.aliasCommonName }}"
  {{- range .Values.subdomains }}
    - "*.{{ . }}.{{ $.Values.dnsDomain }}"
  {{- end }}